name: shyraq_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf