// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYnbwegDlPJw30y-qAUcVZ_OANV5L4OR4',
    appId: '1:373079762422:web:1214abb170eca4b54c93d7',
    messagingSenderId: '373079762422',
    projectId: 'shyraqai',
    authDomain: 'shyraqai.firebaseapp.com',
    storageBucket: 'shyraqai.firebasestorage.app',
    measurementId: 'G-YJ0CMR1N9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEy0icPJDKytrmb7sg3XERPsmEfXoceqk',
    appId: '1:373079762422:android:b30721bafa31fbfd4c93d7',
    messagingSenderId: '373079762422',
    projectId: 'shyraqai',
    storageBucket: 'shyraqai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWW8iRgfr0PrDbXge1HmZQ3PCBPjVZaeU',
    appId: '1:373079762422:ios:026e6bd6c4a65f084c93d7',
    messagingSenderId: '373079762422',
    projectId: 'shyraqai',
    storageBucket: 'shyraqai.firebasestorage.app',
    iosBundleId: 'com.example.shyraqAi',
  );
}
